---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: customer-a
  name: customer-a-prod-efs-pv
spec:
  capacity:
    storage: 30Gi # This is an arbitrary number due to EFS not imposing any limitations but the field is mandatory for Kubernetes
  volumeMode: Filesystem
  mountOptions:
    - accesspoint=fsap-0364e66d62b442cb7 #Accesspoint
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-063816b958da3c200
---
