---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: customer-a
  name: customer-a-prod-efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 30Gi
---